Add `Stdout` exporter, timeout setting, better warning
Liqwid-Labs/liqwid-libs pull request #2
Opened 2023-01-12 04:27 UTC by SeungheonOh

2023-01-12 12:58 UTC, emiflake requested changes
Few minor things. Looks good overall though!

2023-01-12 12:58 UTC, emiflake commented on liqwid-script-export/src/ScriptExport/File.hs
> +    param
Should probably use `when (isNothing param) $ putStrLn ...` instead here, reads a lot more humanly.

2023-01-12 12:58 UTC, emiflake commented on liqwid-script-export/src/ScriptExport/Options.hs
> +  , timeout :: Int
Add a docstring here for what it does

2023-01-12 12:58 UTC, emiflake commented on liqwid-script-export/src/ScriptExport/Options.hs
> +          <> Opt.help "Bulider to use"
```suggestion
          <> Opt.help "Builder to use"
```

2023-01-12 12:58 UTC, emiflake commented on liqwid-script-export/src/ScriptExport/Options.hs
> +          <> Opt.help "Script export server timeout in seconds. (default: 10 minuates)"
```suggestion
          <> Opt.help "Script export server timeout in seconds. (default: 10 minutes)"
```

2023-01-12 13:03 UTC, emiflake commented
Ah, also, please rebase on latest `main`, as it fixes the CI build.

2023-01-12 13:04 UTC, SeungheonOh commented
Awesome, will do. Thank you!

2023-01-13 17:08 UTC, emiflake approved these changes
Good to go!

2023-01-13 17:08 UTC, merged